// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from './routes/_404.tsx';
import * as $_app from './routes/_app.tsx';
import * as $_middleware from './routes/_middleware.ts';
import * as $api_joke from './routes/api/joke.ts';
import * as $greet_name_ from './routes/greet/[name].tsx';
import * as $home from './routes/home.tsx';
import * as $Counter from './islands/Counter.tsx';
import type { Manifest } from '$fresh/server.ts';

const manifest = {
  routes: {
    './routes/_404.tsx': $_404,
    './routes/_app.tsx': $_app,
    './routes/_middleware.ts': $_middleware,
    './routes/api/joke.ts': $api_joke,
    './routes/greet/[name].tsx': $greet_name_,
    './routes/home.tsx': $home,
  },
  islands: {
    './islands/Counter.tsx': $Counter,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
